### ISSUE TITLE
MariaDB Database

### ISSUE THREAD

**Issue by ExceptedPrism3** [ExceptedPrism3/Logger#18]
MariaDB will be included in the upcoming releases

**Comment by DICEALPHAHU** [comment]
Wow, that's cool

**Comment by DICEALPHAHU** [comment]
Dear Prism3 :发自：DICEALPHAHU Huawei Nova 8From : DICEALPHAHU Huawei Nova 8-------- 原始邮件 --------发件人： Prism ***@***.***>日期： 2022年3月5日周六 09:19收件人： ExceptedPrism3/Logger ***@***.***>抄送： DICEALPHAHU ***@***.***>, Comment ***@***.***>主    题： Re: [ExceptedPrism3/Logger] MariaDB Database (Issue #18)
Closed #18.
