### ISSUE TITLE
Shaded dependencies are not relocated

### ISSUE THREAD

**Issue by A248** [ExceptedPrism3/Logger#24]
**Describe the bug**
Shaded dependencies in Logger-Velocity are not relocated. Any dependencies you shade need to be relocated to your own namespace to avoid conflicts with other plugins.

In particular, this causes a conflict with LibertyBans, another Velocity plugin. LibertyBans detected the bug automatically, and a LibertyBans user reported the problem accordingly: https://github.com/A248/LibertyBans/issues/165

**To Reproduce**
1. Install Logger-Velocity
2. Install LibertyBans
3. View report generated by LibertyBans' automated detection of this bug

**Expected behavior**
Logger-Velocity properly relocates its dependencies to its own namespace.

**Screenshots**
![image](https://user-images.githubusercontent.com/74078713/181860418-819cf36f-c4f1-4627-8dfb-8c50f06b4b5a.png)

**Server & Version (please complete the following information):**
 - Version -- Probably from the PostgreSQL branch. This was originally reported by another user.
 - Server Type -- Velocity

**Comment by zRxnx** [comment]
Hello :)
I reported the thing on LibertyBan's repositorie and i found more warns, maybe this is the same but i want to be sure

Have a nice day!
![image](https://user-images.githubusercontent.com/74078713/182008108-d097e026-e5c5-428f-a4cc-a8526164fbfd.png)

**Comment by thelooter** [comment]
Which branch of Logger are you using?

**Comment by thelooter** [comment]
The Postgres Branch is the only branch containing the Postgres Dependency. The Branch is not in a working State currently.

**Comment by A248** [comment]
@zRxnx was probably using the Postgres branch. In any case, there are unrelocated dependencies on both the Improving and PostgreSQL branches. I've made a PR for the Improving branch.
