### ISSUE TITLE
Server throwing SQL exception (when using mysql db) due to chest_interaction 'items' column length being too low

### ISSUE THREAD

**Issue by oklahsam** [ExceptedPrism3/Logger#29]
**Describe the bug**
When a player opens a chest containing a lot of items, the server throws an exception due to the item array string being stored in the 'items' column being longer than the VARCHAR(255) column can fit.  
I edited the database and set the column to VARCHAR(510), 2x the original limit, and still got the error on some chests. Setting it to VARCHAR(1020) made the error stop. I then ran a `SELECT LENGTH(items) FROM chest_interaction` query and saw that some entries were ~950 characters long. I then changed the column type to TEXT, since it has a default limit of 65535, just to make sure I don't get any more errors.

**To Reproduce**
Use the mysql database option for storing logs.
Open a chest with a lot of items. Items with longer names would also affect this, due to the nature of how the information is being stored in the db.

**Expected behavior**
No thrown exceptions, and a log entry for the chest interaction.

**Possible Solutions**
Increase the VARCHAR limit to some much larger number: 
&nbsp;&nbsp;&nbsp;&nbsp;`ALTER TABLE chest_interaction MODIFY items VARCHAR(42069)`
Change from VARCHAR column type to TEXT: 
&nbsp;&nbsp;&nbsp;&nbsp;`ALTER TABLE chest_interaction MODIFY items TEXT`

**Server & Version**
 - 1.19.2
 - PaperMC

**Comment by Sidna02** [comment]
We are well aware of the issue, it is going to be fixed in the next major update.
Thanks for letting us know.
