### ISSUE TITLE
RAM not reading correctly

### ISSUE THREAD

**Issue by Teddy20002** [ExceptedPrism3/Logger#34]
Well i have a 10GB server and Im only using 4.3GB or 4.4GB and im getting a alert from Logger that my ram is all used up.

Im running Paper 1.19.2
Logger Dump file: https://pastebin.com/p6nvrdBz
Screenshots of Discord of usage of ram and game panel of usage of ram: https://photos.app.goo.gl/t2aYrhifNmodYnay5

**Comment by ExceptedPrism3** [comment]
Hello,

May I have a screenshot of your server's startup flags?

**Comment by Teddy20002** [comment]
I think this is it?
java -Xms1G -Xmx10240M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar

Also my name is Maxx i just joined your discord and i didn't know where to asked about this issue.

**Comment by ExceptedPrism3** [comment]
Hi, sorry for the late reply. May I have your discord ID? So I can add you in a ticket. If you still in the discord server

**Comment by Teddy20002** [comment]
Maxx#2354
