### ISSUE TITLE
I placed a sign and modified the text, but it displays an error.

### ISSUE THREAD

**Issue by MOMOas** [ExceptedPrism3/Logger#42]
**Expected behavior**
I placed a sign and modified the text, but it displays an error.

**Screenshots**
![image](https://github.com/ExceptedPrism3/Logger/assets/25352223/115bc88f-8fcb-4de0-bf91-f13953949f3a)

**Server & Version (please complete the following information):**
 - Version Logger-1.8.0.9
 - Server Type purpur-1.20.1-2019

**Comment by httphypixelnet** [comment]
Fixed in #43, please wait for it to be merged.
