### ISSUE TITLE
Support for MC Version 1.20.2

### ISSUE THREAD

**Issue by Redforce04** [ExceptedPrism3/Logger#44]
**Describe the bug**
Currently the plugin does not seem to support 1.20.2 due to an enum error. I assume that the plugin just needs to be updated to 1.20.2, and be rebuilt.
`org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: No enum constant me.prism3.logger.utils.enums.NmsVersions.v1_20_R2`

`Caused by: java.lang.IllegalArgumentException: No enum constant me.prism3.logger.utils.enums.NmsVersions.v1_20_R2`

`at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.2.jar:git-Paper-203]`

**To Reproduce**
1. Install the latest version (1.8.0.9) onto a server with spigot.
2. Run the server.
3. The error will appear as the plugin attempts to load.

**Expected behavior**
The plugin loads like normal.

**Screenshots**
N/A

**Server & Version:**
 - MC Version: 1.20.2
 - Server Type: Bukkit/Spigot/Paper
 - Paper Version: `git-Paper-203` `Implementing API version 1.20.2-R0.1-SNAPSHOT` `Git: fe54a13`
 - Host Information: Java 17 `OpenJDK 64-Bit Server VM 17.0.8.1+1`
 - OS: `Linux 5.10.0-25-amd64 (amd64)`
 - Dockerized via pterodactyl / docker

**Comment by httphypixelnet** [comment]
Fixed in #45, wait for it to get merged in!

**Comment by Redforce04** [comment]
> Fixed in #45, wait for it to get merged in!
Appreciate it. I don't really work with java otherwise I would build it myself. I'm just a C# goober.
