### ISSUE TITLE
Player Head not loading on Discord embed

### ISSUE THREAD

**Issue by AyalX** [ExceptedPrism3/Logger#48]
**Describe the bug**
Player's head don't load on Discord embed except one

**To Reproduce**
1. Setup Discord logs

**Screenshots**
![image](https://github.com/ExceptedPrism3/Logger/assets/25435680/a51d04b6-e1d8-46a2-a139-3ebf96d3e8d3)

**Server & Version:**
 - Version: 18.0.11
 - Server Type: Purpur-2095 1.20.2

**Comment by ExceptedPrism3** [comment]
# Status
Fixed and uploaded on the dev-builds channels over Discord.
Special thanks to **Ayal** for pointing this out! :D
