### ISSUE TITLE
if player kicked by essentialsx for afk - plugin sendticonsole warn

### ISSUE THREAD

**Issue by SL-69** [ExceptedPrism3/Logger#49]
**Describe the bug**
if player kicked by essentialsx for afk - plugin send to console warn
log: https://logpaste.com/eCrmHx0d

**To Reproduce**
1. install essentialsx
2. enable afk kick feature and db type mysql in logger
3. wait for it 

**Expected behavior**
work wothout warn and etc.

**Screenshots**

**Server & Version (please complete the following information):**
Plugin: 
Running Logger: 1.8.0.11
Server:
 Current: git-Purpur-2151 (MC: 1.20.4)*
* You are running the latest version

**Comment by ExceptedPrism3** [comment]
Hi, thanks for the report, it shall be fixed :D

**Comment by Sidna02** [comment]
Issue should be fixed now. 
To solve it from your side you should execute this sql query : 
`ALTER TABLE player_kick MODIFY reason varchar(255);`
