### ISSUE TITLE
[Anvil] - Event gets logged even if its not valid. 

### ISSUE THREAD

**Issue by daksh100sharma** [ExceptedPrism3/Logger#51]
**Desc.**
Anvil Event is logged even if the action was not validated.

**To Reproduce**
1. Go to an Anvil
2. You must have insufficient or 0 XP
3. Re-name an item
4. If you want to use Anvil, use it and take out the item. But....(check point 5th)
5. Your item won't get re-named as you don't have enough XP. But this event gets logged. 
https://i.imgur.com/YzQQPvL.png
https://i.imgur.com/91nODds.png - Database

**Comment by ExceptedPrism3** [comment]
Hello,

Sorry for the late reply first of all and thanks for the report.

It has been fixed in the latest current version: **1.8.0.14**.
