### ISSUE TITLE
Add Support for PostgreSQL

### ISSUE THREAD

**Issue by thelooter** [ExceptedPrism3/Logger#7]
This adds Support for the PostgreSQL Database.

This is an action taking in order to support a wide Array of Usecases

**Comment by 13bm** [comment]
bump, don't know much java but know a few others could help out. Is this still a thing you plan to include?

**Comment by thelooter** [comment]
I'm no longer part of this project, so I can't speak on the plans for it, but you could probably go and ask in the Discord
